
###
GET http://localhost:3000/movies/

###

POST http://localhost:3000/movies/
Content-Type : application/json
{
  "directorId": 6,
  "movieName": "Journy to core of the earth",
  "leadActor": "Jeff Goldblum"
}

###

GET http://localhost:3000/movies/57

###


PUT http://localhost:3000/movies/8
Content-Type : application/json
{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}

###
delete http://localhost:3000/movies/46

###

GET http://localhost:3000/directors/

###
GET http://localhost:3000/directors/10/movies/